[package]
name = "cxd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
const_format = "0.2.32"
exec = "0.3.1"
pico-args = { version = "0.5.0", features = ["short-space-opt"] }
rusqlite = "0.31.0"

[dev-dependencies]
assert_cmd = "2.0.15"
predicates = "3.1.2"
